# Generated by Django 6.1 on 2026-09-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='biens/'),
        ),
    ]
